Module6 task3
htmlacademy-react/454795-what-to-watch-7 pull request #12
Opened 2021-07-13 07:37 UTC by CptKokao

2021-07-13 10:21 UTC, Razzwan requested changes

2021-07-13 10:21 UTC, Razzwan commented on project/public/img/icons/tick.svg
> +<g>
пустые можно удалить

2021-07-13 10:21 UTC, Razzwan commented on project/src/components/app/app.jsx
> +  if (isCheckedAuth(statusAuth)) {
`isCheckedAuth` не соответсвует содержимому. Лучше переименовать в `isUserGuest` или `isNotAuthorized`

2021-07-13 10:21 UTC, Razzwan commented on project/src/components/common/BtnMyList/BtnMyList.jsx
> +  // как быудто на сервере данные не успели измениться и мне возвращается старые данные
Да, так бывает. Это потому что кеш на сервере не успел обновиться. Чтоб избежать этого эффекта можно делать изменение самостоятельно на клиенте.

2021-07-13 10:21 UTC, Razzwan commented on project/src/components/common/BtnMyList/BtnMyList.jsx
> +  function checkFavorite() {
название функции не соответсвует содержимому. Лучше назвать: `getFavoriteById` или `isFavoriteExists`

2021-07-13 10:21 UTC, Razzwan commented on project/src/components/common/FormReview/FormReview.jsx
> +  const [valid, seValid] = React.useState(false);
seValid -> setValid

2021-07-13 10:21 UTC, Razzwan commented on project/src/components/pages/AddReview/AddReview.jsx
> +    // тогда запрос к сереверу отправлять не нужно, иначе запросить фильм
Где, в таком случае, мы очищаем активный фильм?

2021-07-13 10:21 UTC, Razzwan commented on project/src/store/actions.js
> +  redirectToRoute: (url) => ({
Похоже, этот экшн нигде не используется. Надо удалить в таком случае

2021-07-14 07:55 UTC, CptKokao commented on project/src/components/pages/AddReview/AddReview.jsx
> +    // тогда запрос к сереверу отправлять не нужно, иначе запросить фильм
Если пользователь загрузится со страницы /films/:id/add-review, то в таком случае activeFilm еще пустой и нужно отправить запрос на получение данных.
Если пользователь перешел с / , то activeFilm уже имеет данные и хранится в store, поэтому повторно отправлять запрос не нужно.

2021-07-15 06:10 UTC, Razzwan approved these changes

2021-07-15 06:10 UTC, merged