Module3 task1
htmlacademy-react/454795-what-to-watch-7 pull request #5
Opened 2021-06-14 22:00 UTC by CptKokao

2021-06-15 11:26 UTC, Razzwan requested changes

2021-06-15 11:26 UTC, Razzwan commented on project/src/components/common/FormReview/FormReview.jsx
> +      ...review,
Лучше отделить эти два значения друг от друга и поместить их каждый в отдельное состояние

2021-06-15 11:26 UTC, Razzwan commented on project/src/components/common/FormReview/FormReview.jsx
> +              const index = [...Array(10)].length - i;
Уже готовый индекс есть строчкой выше в переменной `i`

2021-06-15 11:26 UTC, Razzwan commented on project/src/components/common/ListCards/ListCards.jsx
> +    films.map((card) => (
В этом компоненте должна быть какая-то разметка, которая обрамляет карточки фильмов. Без такой разметки этот компонент имеет мало смысла

2021-06-15 11:26 UTC, Razzwan commented on project/src/components/pages/AddReview/AddReview.jsx
> +      name: PropTypes.string.isRequired,
Общие типы можно вынести в отдельный файл

2021-06-15 11:26 UTC, Razzwan commented on project/src/components/pages/Details/Details.jsx
> +      name: PropTypes.string.isRequired,
Общие типы можно вынести в отдельный файл

2021-06-15 11:26 UTC, Razzwan commented on project/src/components/pages/Film/Film.jsx
> +      name: PropTypes.string.isRequired,
Общие типы можно вынести в отдельный файл

2021-06-15 11:26 UTC, Razzwan commented on project/src/components/pages/Main/Main.jsx
> +            <ListCards films={films} />
Вот этот блок с классом `catalog__films-list` должен быть внутри компонента `ListCards `

2021-06-15 11:26 UTC, Razzwan commented on project/src/components/pages/Main/Main.jsx
> +        {/* Footer */}
Комментарий, который в точности повторяет название компонента имеет мало смысла, Лучше его удалить

2021-06-15 11:26 UTC, Razzwan commented on project/src/components/pages/Player/Player.jsx
> +      <video src={films[0].videoLink} className="player__video" poster={films[0].previewImage}></video>
Лучше в начале компонента объявить/определить фильм, который мы будем здесь использовать, чтоб не писать каждый раз `films[0]` и позже мы можем заменить этот фильм на код, который будет приходить из хранилища, при этом, ничего не придется менять

2021-06-15 11:26 UTC, Razzwan commented on project/src/components/pages/Review/Review.jsx
> +  const film = films[id - 1] ;
Это тод работает только потому, что id не приходят с сервера. Лучше его заменить на какой-то другой. Возможно, нужно обсудить этот вопрос детально

2021-06-15 11:26 UTC, Razzwan commented on project/src/components/pages/Review/Review.jsx
> +      name: PropTypes.string.isRequired,
Лучше вынести в отдельный файл

2021-06-15 17:40 UTC, CptKokao commented on project/src/components/common/FormReview/FormReview.jsx
> +              const index = [...Array(10)].length - i;
Т.к. рейтинг в верстке начинается с 10 и заканчивается 1, то мне нужно было сделать так, чтобы в первой итерации цикла индекс был 10. Как раз такая запись `[...Array(10)].length - i;` реализует это.
---
Поправил [...Array(10)] на array, который передается в аргументах.
`{[...Array(10)].map((item, i, array) => {
              const index = array.length - i;`

2021-06-15 17:44 UTC, CptKokao commented on project/src/components/common/FormReview/FormReview.jsx
> +      ...review,
Поправил

2021-06-15 17:52 UTC, CptKokao commented on project/src/components/common/ListCards/ListCards.jsx
> +    films.map((card) => (
Обернул в `<div className="catalog__films-list"></div>`

2021-06-15 17:54 UTC, CptKokao commented on project/src/components/pages/Main/Main.jsx
> +            <ListCards films={films} />
Исправил.

2021-06-15 18:17 UTC, CptKokao commented on project/src/components/pages/Player/Player.jsx
> +      <video src={films[0].videoLink} className="player__video" poster={films[0].previewImage}></video>
Исправил.

2021-06-16 19:08 UTC, CptKokao commented on project/src/components/pages/AddReview/AddReview.jsx
> +      name: PropTypes.string.isRequired,
Вынес в отдельный файл.

2021-06-16 19:08 UTC, CptKokao commented on project/src/components/pages/Details/Details.jsx
> +      name: PropTypes.string.isRequired,
Вынес в отдельный файл.

2021-06-16 19:08 UTC, CptKokao commented on project/src/components/pages/Review/Review.jsx
> +      name: PropTypes.string.isRequired,
Вынес в отдельный файл.

2021-06-16 19:09 UTC, CptKokao commented on project/src/components/pages/Film/Film.jsx
> +      name: PropTypes.string.isRequired,
Вынес в отдельный файл.

2021-06-16 19:11 UTC, CptKokao commented on project/src/components/pages/Review/Review.jsx
> +  const film = films[id - 1] ;
Этот момент пока оставил без исправлений, но буду иметь ввиду при дальнейшей работе.

2021-06-18 07:12 UTC, merged